### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Patrick01-Foshay**

### CODE REVIEW

**Comment by Le0nidas101** [comment]
Sup bro

**Review by Le0nidas101 — CHANGES_REQUESTED** [review]
Commit changes

**Review by Patrick01-Foshay — COMMENTED** [review]
yeah that will work

**Comment by Le0nidas101** [comment]
Boomer

**Review by Le0nidas101 — COMMENTED** [review]
That’s okay

**Pull request merged**
